config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  resources :users
  root 'toppages#index'
  resources :histories do
    post 'bulk_create', on: :collection
    post 'link', on: :member
    put 'unlink', on: :member
  end
  get 'top' => 'toppages#top'
  get 'callback' => 'toppages#callback'
  get 'login' => 'toppages#login'
  get 'money' => 'toppages#money'
  namespace 'api' do
    namespace 'v1' do
      namespace 'user' do
        post 'bulk_create_histories'
      end
    end
  end
end

app/models/history.rb
class History < ApplicationRecord
  include Zaim::Zaim
  
  MEMO_STRING = '[HM AutomaticInput]'

  enum process: { train_fare: 1, charge: 2, ticket: 3, others: 6, bus_fare_2: 13, bus_fare: 15, window: 25, bus_charge: 31, purchase: 70, point_charge: 72, purchase_2: 198}
  enum link_status: { unlinked: 0, linked: 1 }

  belongs_to :user

  def ===(other)
    History.comparable_attr.each do |attr|
      return false if send(attr) != other.send(attr)
    end
    return true
  end

  def link
    if linked?
      return false
    else
      money = (charge? || bus_charge?) ? transfer : payment
      self.linked_at = Time.now.strftime("%F")
      self.zaim_id = money['money']['id']
      self.save!
      self.linked!
      return true
    end
  end

  def unlink
    if !linked?
      return false
    else
      (charge? || bus_charge?) ? delete('transfer') : delete('payment')
      self.unlinked!
      self.linked_at = nil
      self.zaim_id = nil
      self.save!
      return true
    end
  end
  
  class << self
    YEAR_PREFIX = 20
    def comparable_attr
      [:console, :process, :in_station, :out_station, :date, :balance]
    end

    def new_from_ic(attrs, balance)
      attrs.select!{|attr| attr['process'] != 0} 
      attrs.map!.with_index do |attr, i|
        attr['date'] = YEAR_PREFIX.to_s + attr['date'].to_s
        if i == 0
          attr['amount'] = balance - attr['balance']
        else
          attr['amount'] = attrs[i-1]['balance'] - attr['balance']
        end
        attr
      end
      attrs.map{|attr| History.new(attr)} 
    end
  end

  private
  def to_zaim
    zaim_hash = 
      if train_fare?
        { mapping: 1,
          category_id: 103,
          genre_id: 10301,
          amount: amount,
          date: date,
          from_account_id: 6,
          comment: "#{in_station}→#{out_station}",
        }
      elsif ticket?
        { mapping: 1,
          category_id: 103,
          genre_id: 10303,
          amount: amount,
          date: date,
          from_account_id: 6,
          comment: '',
        }
      elsif others?
        { mapping: 1,
          category_id: 103,
          genre_id: 10303,
          amount: amount,
          date: date,
          from_account_id: 6,
          comment: '',
        }
      elsif bus_fare?
        { mapping: 1,
          category_id: 103,
          genre_id: 10303,
          amount: amount,
          date: date,
          from_account_id: 6,
          comment: '',
        }
      elsif bus_fare_2?
        { mapping: 1,
          category_id: 103,
          genre_id: 10303,
          amount: amount,
          date: date,
          from_account_id: 6,
          comment: '',
        }
      elsif purchase?
        { mapping: 1,
          category_id: 199,
          genre_id: 19905,
          amount: amount,
          date: date,
          from_account_id: 6,
          comment: '',
        }
      elsif purchase_2?
        { mapping: 1,
          category_id: 199,
          genre_id: 19905,
          amount: amount,
          date: date,
          from_account_id: 6,
          comment: '',
        }
      elsif window?
        { mapping: 1,
          category_id: 199,
          genre_id: 19905,
          amount: amount,
          date: date,
          from_account_id: 6,
          comment: '',
        }
      elsif charge?
        { mapping: 1,
          amount: -amount,
          date: date,
          from_account_id: 1,
          to_account_id: 6,
          comment: '',
        }
      elsif bus_charge?
        { mapping: 1,
          amount: -amount,
          date: date,
          from_account_id: 1,
          to_account_id: 6,
          comment: '',
        }
      elsif point_charge?
        { mapping: 1,
          amount: -amount,
          date: date,
          from_account_id: 1,
          to_account_id: 6,
          comment: '',
        }
      end
    zaim_hash[:comment] = "#{MEMO_STRING}\n#{zaim_hash[:comment]}"
    return zaim_hash
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_history, only: [:show, :edit, :update, :destroy, :link, :unlink]

  def index
    @histories = current_user.histories.order('id')
  end

  def show
  end

  def new
    @history = History.new
  end

  def edit
  end

  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
    end
  end

  def link
    @history.link
    render :show
  end

  def unlink
    @history.unlink
    render :show
  end

  private
    def set_history
      @history = History.find(params[:id])
    end

    def history_params
      params.require(:history).permit(:console, :process, :date, :in_station, :out_station, :balance, :amount)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history, local: true) do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :console %>
    <%= form.text_field :console %>
  </div>

  <div class="field">
    <%= form.label :action %>
    <%= form.text_field :action %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :in_station_line %>
    <%= form.text_field :in_station_line %>
  </div>

  <div class="field">
    <%= form.label :in_station %>
    <%= form.text_field :in_station %>
  </div>

  <div class="field">
    <%= form.label :out_station_line %>
    <%= form.text_field :out_station_line %>
  </div>

  <div class="field">
    <%= form.label :out_station %>
    <%= form.text_field :out_station %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.number_field :balance %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histories</h1>

<table>
  <thead>
    <tr>
      <th>Console</th>
      <th>Process</th>
      <th>Date</th>
      <th>In station</th>
      <th>Out station</th>
      <th>Amount</th>
      <th>Balance</th>
      <th>Status</th>
      <th>Linked at</th>
      <th>Zaim ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.console %></td>
        <td><%= history.process %></td>
        <td><%= history.date %></td>
        <td><%= history.in_station %></td>
        <td><%= history.out_station %></td>
        <td><%= history.amount %></td>
        <td><%= history.balance %></td>
        <td><%= history.link_status %></td>
        <td><%= history.linked_at %></td>
        <td><%= history.zaim_id %></td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Console:</strong>
  <%= @history.console %>
</p>

<p>
  <strong>Process:</strong>
  <%= @history.process %>
</p>

<p>
  <strong>Date:</strong>
  <%= @history.date %>
</p>

<p>
  <strong>In station:</strong>
  <%= @history.in_station %>
</p>

<p>
  <strong>Out station:</strong>
  <%= @history.out_station %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @history.balance %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @history.amount %>
</p>

<p>
  <strong>Link Status:</strong>
  <%= @history.link_status %>
</p>

<p>
  <strong>Linked at:</strong>
  <%= @history.linked_at %>
</p>

<p>
  <strong>Zaim ID:</strong>
  <%= @history.zaim_id %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Link', link_history_path(@history), method: :post %> |
<%= link_to 'Unlink', unlink_history_path(@history), method: :put %> |
<%= link_to 'Back', histories_path %>